<?php
    require_once("models/database.php");
    require_once("models/Login.php");
    require_once("models/Usuario.php");
    require_once("models/Cargo.php");
    require_once("models/Reporte.php");
    require_once("models/Rol.php");
    require_once("models/Tipo_documento.php");
?>